import './globals.css'
import type { Metadata } from 'next'
import Page from './page'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <main className='flex justify-center items-center h-screen'>
          <div className='flex justify-center items-center flex-col'>
            <Page/>
            <Page/>
            <Page/>
            <Page/>
            <Page/>
          </div>
        </main>
      </body>
    </html>
  )
}
