import './globals.css'
import type { Metadata } from 'next'
import Page from './page'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
      <body className='flex flex-col items-center bg-slate-300 dark:bg-slate-900'>
        <Page/>
      </body>
    </html>
  )
}
